#!/usr/bin/env bash
# Prepare local KUKU demo files and variables.
# Typical use: ./scripts/kuku-bootstrap.sh && source .kuku-demo.env

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

usage() {
  cat <<'EOF'
KUKU local demo bootstrap — prep only.

What it does on every run:
- rewrites web/.env with NEXT_PUBLIC_API_BASE_URL (prefers data/config.yaml api.port, falls back to 5300; override with LANG_BOT_HTTP_PORT)
- resets the demo API key in data/langbot.db to demo-kuku-key
- reads one bot UUID from the bots table
- writes .kuku-demo.env for curl examples

What it does NOT do:
- it does not start uv run main.py
- it does not start pnpm dev
- it does not create a bot for you

Usage:
  ./scripts/kuku-bootstrap.sh

If LangBot listens on another port (check startup log: \"Running on http://0.0.0.0:PORT\"):
  LANG_BOT_HTTP_PORT=15300 ./scripts/kuku-bootstrap.sh

After running successfully:
  source .kuku-demo.env
  uv run main.py
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -gt 0 ]]; then
  echo "Unknown option: $1" >&2
  usage >&2
  exit 1
fi

if ! command -v sqlite3 >/dev/null 2>&1; then
  echo "error: sqlite3 not found (install SQLite CLI)" >&2
  exit 1
fi

API_HOST="${LANG_BOT_HTTP_HOST:-127.0.0.1}"
CONFIG_PORT="$(
  awk '
    $0 ~ /^api:[[:space:]]*$/ {
      in_api = 1
      next
    }
    in_api && $0 ~ /^[^[:space:]]/ {
      in_api = 0
    }
    in_api && $0 ~ /^[[:space:]]+port:[[:space:]]*/ {
      line = $0
      sub(/^[[:space:]]+port:[[:space:]]*/, "", line)
      gsub(/["'\''[:space:]]/, "", line)
      print line
      exit
    }
  ' "$REPO_ROOT/data/config.yaml" 2>/dev/null || true
)"
API_PORT="${LANG_BOT_HTTP_PORT:-${CONFIG_PORT:-5300}}"

mkdir -p "$REPO_ROOT/web"
printf 'NEXT_PUBLIC_API_BASE_URL=http://%s:%s\n' "$API_HOST" "$API_PORT" >"$REPO_ROOT/web/.env"
echo "Wrote $REPO_ROOT/web/.env (API ${API_HOST}:${API_PORT})"

db="$REPO_ROOT/data/langbot.db"
if [[ ! -f "$db" ]]; then
  echo ""
  echo "No $db yet."
  echo "Next:"
  echo "  1. Start LangBot: uv run main.py"
  echo "  2. Start the web UI: cd web && pnpm install && pnpm dev"
  echo "  3. Open http://127.0.0.1:3000"
  echo "  4. If prompted, create a local account and sign in"
  echo "  5. Go to Bots, click Create Bot, and save one Discord bot"
  echo "  6. Stop LangBot and run ./scripts/kuku-bootstrap.sh again"
  exit 0
fi

sqlite3 "$db" "DELETE FROM api_keys WHERE name='demo-kuku' OR key='demo-kuku-key';"
sqlite3 "$db" "INSERT INTO api_keys (name,key,description) VALUES ('demo-kuku','demo-kuku-key','Temporary local API key for KUKU demo (scripts/kuku-bootstrap.sh)');"

bot_uuid=$(sqlite3 "$db" "SELECT uuid FROM bots WHERE adapter='discord' LIMIT 1;" || true)
if [[ -z "$bot_uuid" ]]; then
  bot_uuid=$(sqlite3 "$db" "SELECT uuid FROM bots LIMIT 1;" || true)
fi

if [[ -z "$bot_uuid" ]]; then
  echo ""
  echo "Reset demo API key to demo-kuku-key in $db."
  echo "No bot found in the bots table yet, so .kuku-demo.env was not written."
  echo "Next:"
  echo "  1. Start LangBot: uv run main.py"
  echo "  2. Start the web UI: cd web && pnpm install && pnpm dev"
  echo "  3. Open http://127.0.0.1:3000"
  echo "  4. If prompted, create a local account and sign in"
  echo "  5. Go to Bots, click Create Bot, and save one Discord bot"
  echo "  6. Stop LangBot and run ./scripts/kuku-bootstrap.sh again"
  exit 0
fi

env_file="$REPO_ROOT/.kuku-demo.env"
{
  printf '%s\n' '# Generated by scripts/kuku-bootstrap.sh — do not commit'
  printf "%s\n" "export KUKU_API_BASE_URL='http://${API_HOST}:${API_PORT}'"
  printf "%s\n" "export KUKU_API_KEY='demo-kuku-key'"
  printf "%s\n" "export KUKU_BOT_UUID='${bot_uuid}'"
  printf "%s\n" "export KUKU_GROUP_ID='demo-group'"
} >"$env_file"

echo "Reset demo API key to demo-kuku-key in $db"
echo "Wrote $env_file"
echo ""
echo "  source $env_file"
echo ""
echo "Start backend (other terminal): uv run main.py"
echo "Sample:"
echo "  curl -s \"\${KUKU_API_BASE_URL}/api/v1/kuku/personas\" -H \"X-API-Key: \${KUKU_API_KEY}\""
